---
title: "FlowDraft"
author: "Mikias HW"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(flowCore)
library(ggcyto)
```

# flowFrame
```{r}
file.name <- system.file("extdata","0877408774.B08",
package="flowCore")

x <- read.FCS(file.name, alter.names=TRUE, transformation=FALSE)

summary(x)
```

# flowSet
```{r}
# fs <- read.flowSet(path = fcs.dir)

fcs.dir <- system.file("extdata",
"compdata",
"data",
package="flowCore")

frames <- lapply(dir(fcs.dir, full.names=TRUE), read.FCS)

names(frames) <- sapply(frames, keyword, "SAMPLE ID")

fs <- as(frames, "flowSet")

fs

sampleNames(fs)

# Extract metadata
phenoData(fs)$Filename <- fsApply(fs,keyword, "$FIL")

pData(phenoData(fs))

summary(fs[2])
```

# Visualize
```{r}
# ggcyto
autoplot(fs, "FSC-H", "SSC-H")

```

# Compensation
```{r}
fcsfiles <- system.file("extdata",
"compdata",
"data",
package="flowCore")

# 


fs <- read.flowSet(fcsfiles)

x <- fs[[1]]

comp_list <- spillover(x)
```

```{r}
library(healthyFlowData)

data(hd)

fs <- hd.flowSet

fs

sampleNames(fs)

summary(fs[1])

autoplot(fs[1], "CD4", "CD8")


```



